<a href="https://colab.research.google.com/github/vrajsavliya/ml_learning/blob/main/Pandas_1_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas

best for manuplating the whole dataset.

*.. Pandas have two objects 1)series
2)dataframe

In [2]:
import numpy as np
import pandas as pd # is used to import pandas

## Series from lists

There are different ways to build the series

In [3]:
# using arrays or can say python list
country =['India','pak','USA','Nepal']
pd.Series(country)

0    India
1      pak
2      USA
3    Nepal
dtype: object

In [5]:
#Integer type series
runs = [13,12,3,4,5,62,4,533,5]
pd.Series(runs,dtype=np.int32)

0     13
1     12
2      3
3      4
4      5
5     62
6      4
7    533
8      5
dtype: int32

In [7]:
# Custom indexing and integer list

marks = [80,99,75,89]
subjects = ['english','math','hindi','SS']

pd.Series(marks,index=subjects) #Custom index bana ne ke liyee best hai yee

english    80
math       99
hindi      75
SS         89
dtype: int64

In [10]:
# setting a name
pd.Series(marks,index=subjects,name='Vraj svliya ke marks')

english    80
math       99
hindi      75
SS         89
Name: Vraj svliya ke marks, dtype: int64

## Series from dict

In [12]:
marks = {
    'maths' : 99,
    'English' : 89,
    'Hindi' : 79,
    'Science' : 86
}

marks_series = pd.Series(marks,name = 'Vraj Savliya ke Marks')
marks_series

maths      99
English    89
Hindi      79
Science    86
Name: Vraj Savliya ke Marks, dtype: int64

## Series Attributes

In [ ]:
#size

z#tell about the number of items or can say tell about the size